checkoutLocation: src/github.com/Jernesstar/VolcanicEngine
workspaceLocation: /workspace/VolcanicEngine
image:
  file: Dockerfile
ports:
  - port: 6080
    protocol: "http"
tasks:
  - command: "git pull && git submodule update --init \
              && scripts/premake.sh && scripts/build.sh"